PYTHON = python

test: historic_test example geo_example runner_test


historic_test:		
	$(PYTHON) historic_affor_test.py
example:
	$(PYTHON) example.py
geo_example:
	$(PYTHON) geo_example.py
runner_test:
	$(PYTHON) runner_test.py
